// Donations
export const GET_DONATIONS = 'GET_DONATIONS';
export const ADD_DONATION = 'ADD_DONATION';
export const DELETE_DONATION = 'DELETE_DONATION';
export const DONATIONS_LOADING = 'DONATIONS_LOADING';
export const CREATE_DONATIONS = 'CREATE_DONATIONS';
export const DONATIONS_CREATING = 'DONATIONS_CREATING';

// Donors
export const GET_DONORS = 'GET_DONORS';
export const ADD_DONOR = 'ADD_DONOR';
export const DELETE_DONOR = 'DELETE_DONOR';
export const DONORS_LOADING = 'DONORS_LOADING';
export const GET_ELIGIBLE_DONORS = 'GET_ELIGIBLE_DONORS';
export const DONOR_ADDED = 'DONOR_ADDED';
export const DONOR_ADD_FAILED = 'DONOR_ADD_FAILED';
export const DONOR_SUCCESS = 'DONOR_SUCCESS';

// User
export const USER_LOADING = "USER_LOADING";
export const USER_AUTHENTICATED = "USER_AUTHENTICATED";
export const REGISTER_USER = "REGISTER_USER";

// Auhtentication
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';